<a href="https://colab.research.google.com/github/vahenoorsingh/ML-Models/blob/main/Building_Neural_Networks_with_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import torch

In [11]:
if torch.cuda.is_available():
  device = "cuda"
elif torch.backends.mps.is_available():
  device = "mps"
else:
  device = "cpu"

Linear Regression using tensors

In [12]:
from sklearn.datasets import fetch_california_housing

In [13]:
housing_data = fetch_california_housing()

X = housing_data.data
y = housing_data.target

In [16]:
from sklearn.model_selection import train_test_split

X_train_val, X_test, y_train_val, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train, X_valid, y_train, y_valid = train_test_split(X_train_val, y_train_val, test_size=0.2, random_state=42)

In [20]:
X_train = torch.FloatTensor(X_train)
X_valid = torch.FloatTensor(X_valid)
X_test = torch.FloatTensor(X_test)

means = X_train.mean(dim = 0, keepdim=True)
stds = X_train.std(dim=0, keepdims=True)

X_train = (X_train - means) / stds
X_valid = (X_valid - means) / stds
X_test = (X_test - means) / stds


y_train = torch.FloatTensor(y_train).reshape(-1, 1)
y_valid = torch.FloatTensor(y_valid).reshape(-1, 1)
y_test = torch.FloatTensor(y_test).reshape(-1, 1)

In [26]:
torch.manual_seed(42)

n_features = X.shape[1]
w = torch.rand((n_features, 1), requires_grad=True)
b = torch.tensor(0., requires_grad=True)

In [27]:
learning_rate = 0.4
n_epochs= 20

for i in range(n_epochs):
  y_pred = X_train @ w + b
  loss = ((y_pred - y_train) ** 2).mean()
  loss.backward()
  with torch.no_grad():
    w -= learning_rate * w.grad
    b -= learning_rate * b.grad
    w.grad.zero_()
    b.grad.zero_()
    print(f"Epoch {i + 1}/{n_epochs}, Loss: {loss.item()}")

Epoch 1/20, Loss: 7.592710971832275
Epoch 2/20, Loss: 1.2913048267364502
Epoch 3/20, Loss: 0.8040429353713989
Epoch 4/20, Loss: 0.7096336483955383
Epoch 5/20, Loss: 0.6748923659324646
Epoch 6/20, Loss: 0.6548479795455933
Epoch 7/20, Loss: 0.6397308111190796
Epoch 8/20, Loss: 0.6269952654838562
Epoch 9/20, Loss: 0.6158507466316223
Epoch 10/20, Loss: 0.6059696078300476
Epoch 11/20, Loss: 0.597161591053009
Epoch 12/20, Loss: 0.5892873406410217
Epoch 13/20, Loss: 0.5822333693504333
Epoch 14/20, Loss: 0.5759031176567078
Epoch 15/20, Loss: 0.5702133178710938
Epoch 16/20, Loss: 0.565091073513031
Epoch 17/20, Loss: 0.5604732632637024
Epoch 18/20, Loss: 0.5563040971755981
Epoch 19/20, Loss: 0.5525348782539368
Epoch 20/20, Loss: 0.5491229295730591


In [28]:
X_new = X_test[0:3]

with torch.no_grad():
  y_pred = X_new @ w + b

print(y_pred)

tensor([[47.1970],
        [50.9137],
        [53.6938]])


In [29]:
import torch.nn as nn
torch.manual_seed(42)
model = nn.Linear(in_features=n_features, out_features=1)

In [31]:
for param in model.named_parameters():
  print(param)

('weight', Parameter containing:
tensor([[ 0.2703,  0.2935, -0.0828,  0.3248, -0.0775,  0.0713, -0.1721,  0.2076]],
       requires_grad=True))
('bias', Parameter containing:
tensor([0.3117], requires_grad=True))


In [32]:
model(X_train[:2])

tensor([[0.0786],
        [0.1613]], grad_fn=<AddmmBackward0>)